[package]
name = "constraints"
version = "0.1.0"
edition = "2021"

[dependencies]
fast-math = "0.1.1"
rand = "0.8.5"
raylib = "5.0.2"
serde = "1.0.215"
serde_derive = "1.0.215"
serde_json = "1.0.133"

[profile.release]
debug = true
